matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9
script:
  - set -o pipefail
  - xcodebuild test -scheme BlurEditor -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7" | xcpretty -c
